# Generated by Django 5.2 on 2026-07-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closing_hours',
            field=models.TimeField(default=None),
        ),
    ]
