# Generated by Django 5.2 on 2026-07-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='protriat',
            new_name='protrait',
        ),
    ]
