# Generated by Django 5.2 on 2026-07-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_rename_protriat_chef_protrait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='protrait',
            new_name='portrait',
        ),
    ]
